// Hospital Authentication Actions
export const HOSPITAL_REGISTER = 'HOSPITAL_REGISTER';
export const HOSPITAL_REGISTER_SUCCESS = 'HOSPITAL_REGISTER_SUCCESS';
export const HOSPITAL_REGISTER_ERROR = 'HOSPITAL_REGISTER_ERROR';

export const HOSPITAL_LOGIN = 'HOSPITAL_LOGIN';
export const HOSPITAL_LOGIN_SUCCESS = 'HOSPITAL_LOGIN_SUCCESS';
export const HOSPITAL_LOGIN_ERROR = 'HOSPITAL_LOGIN_ERROR';

export const HOSPITAL_LOGOUT = 'HOSPITAL_LOGOUT';

// Organ Inventory Actions
export const FETCH_ORGAN_INVENTORY = 'FETCH_ORGAN_INVENTORY';
export const FETCH_ORGAN_INVENTORY_SUCCESS = 'FETCH_ORGAN_INVENTORY_SUCCESS';
export const FETCH_ORGAN_INVENTORY_ERROR = 'FETCH_ORGAN_INVENTORY_ERROR';

export const SEARCH_ORGANS = 'SEARCH_ORGANS';
export const SEARCH_ORGANS_SUCCESS = 'SEARCH_ORGANS_SUCCESS';
export const SEARCH_ORGANS_ERROR = 'SEARCH_ORGANS_ERROR';

// Hospital Requests Actions
export const FETCH_HOSPITAL_REQUESTS_MADE = 'FETCH_HOSPITAL_REQUESTS_MADE';
export const FETCH_HOSPITAL_REQUESTS_MADE_SUCCESS = 'FETCH_HOSPITAL_REQUESTS_MADE_SUCCESS';
export const FETCH_HOSPITAL_REQUESTS_MADE_ERROR = 'FETCH_HOSPITAL_REQUESTS_MADE_ERROR';

export const FETCH_HOSPITAL_REQUESTS_RECEIVED = 'FETCH_HOSPITAL_REQUESTS_RECEIVED';
export const FETCH_HOSPITAL_REQUESTS_RECEIVED_SUCCESS = 'FETCH_HOSPITAL_REQUESTS_RECEIVED_SUCCESS';
export const FETCH_HOSPITAL_REQUESTS_RECEIVED_ERROR = 'FETCH_HOSPITAL_REQUESTS_RECEIVED_ERROR';
